### ISSUE TITLE
Smooshables need likelihood scalers

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#1]
Right now everything is stored in terms of probabilities, which is lovely and fast, though we need to avoid underflow. 

I propose that they have a member variable that just stores a log likelihood, which scales the overall likelihood of each entry of each of the matrices.

This would also be handy for defining a smooshable from an alignment of a read to a germline gene, in which the part not incorporated in the smooshable could have its likelihood plopped into a simple variable.

(_Reminder:_ both of the marginal and the Viterbi probabilities need to be scaled.)

**Comment by matsen** [comment]
Renaming to "scaler" to correspond with libpll.

**Comment by matsen** [comment]
* scalers are exponents
* to get to the correct log likelihood, we need to subtract by some multiple of the scaler (https://github.com/xflouris/libpll/blob/dev/src/core_likelihood.c#L353)

Also, no need to have scalers in germline.

**Comment by matsen** [comment]
Given that we may be looking at zero likelihoods from dummy paths, it seems to me that we should have an assertion in the rescaling code that keeps us from getting an infinite loop in the case of exactly zero likelihood.

**Comment by dunleavy005** [comment]
Since the 0's will be within matrices that have non-zero values, I don't see how the infinite loop happens.  Right now, the SCALE_FACTOR only multiplies if all entries of the matrix are less than SCALE_THRESHOLD, and since our matrices are mixed, we don't ever have a matrix just with 0's so it will stop at some point?

**Comment by matsen** [comment]
Would still be good to have an assertion that matrices aren't all zero.
