### ISSUE TITLE
What do we do with N bases in the middle of a read?

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#19]
Partis' solution is to give a 1/4 emission probability to an N base, as described in ham's `EmissionLogprob`.

It seems clear to us that the emission probability should be 1 for an N, because N represents any base. We are not emitting a random variable, we are emitting a set.

Practically speaking in the code, our current solution is to map N's to (alphabet.size+1) and an extra row of the germline emission matrix with 1's. We can fill this row with 0.25 for the time being to match partis.

**Comment by dunleavy005** [comment]
closed by #45
