### ISSUE TITLE
B-W or stochastic EM?

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#22]
How quickly can we do B-W or stochastic EM using linearham? 

![screenshot 2016-10-24 at 1 40 05 pm](https://cloud.githubusercontent.com/assets/112708/19663128/791ee8b8-99ef-11e6-9322-091cfc5ead7c.png)
![screenshot 2016-10-24 at 1 40 35 pm](https://cloud.githubusercontent.com/assets/112708/19663129/7a6b0026-99ef-11e6-8135-e6d054d90cde.png)

From

> Lam, T. Y., & Meyer, I. M. (2010). Efficient algorithms for training the parameters of hidden Markov models using stochastic expectation maximization (EM) training and Viterbi training. Algorithms for Molecular Biology: AMB, 5, 38. https://doi.org/10.1186/1748-7188-5-38

**Comment by dunleavy005** [comment]
Also, can we do naive rearrangement sampling (i.e. sample from posterior distribution of hidden states)?

**Comment by dunleavy005** [comment]
we are now doing importance sampling to re-weight posterior trees, no need for training
