### ISSUE TITLE
NRegion and SmooshableNRegion

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#3]
Given emission probabilities for the various states, and a vector of N-region length prior probabilities, we need an object equivalent to a Germline that contains that information.

Then given an observed sequence (vector of indices) and an NRegion we can have a SmooshableNRegion analogous to the SmooshableGermline.

For purposes of comparison to ham, having the prior probabilities be geometric for first go would seem sage.

**Comment by matsen** [comment]
As shown here:

![1 pdf](https://cloud.githubusercontent.com/assets/112708/15677425/140f20fe-26ff-11e6-99df-011bdc6a1ce9.png)

there are distinct probabilities of transitioning into various points in the germline gene depending on if we are going directly from the init state (no insertions) versus if there are a nonzero number of insertions (from the insertion state). 

This is a specific case of allowing some dependence of downstream probabilities on the number of insertions. How should we accommodate this sort of thing?

**Comment by matsen** [comment]
Ah, it could be done by having two Germlines for every germline gene, the first of which has landing probabilities for coming in directly from the init state, and the second of which has those from the insert state. Then we could immediately smoosh the corresponding Insertion smooshables onto them: the first would have zero probability of any insertion, and the second would be the usual Insertion.

**Comment by matsen** [comment]
The current plan is to have all of this information stored in the Germline gene. When presented with a read and a left flex for the N region, build an "NG" smooshable that includes the N region using the corresponding transition probabilities, and an "XG" smooshable that does not. 

So I propose that Germline also get a landing_N vector of Eigen::Vectors which is indexed by the current NTI base, as well as an n_bases x n_bases matrix specifying the emission probabilities (columns) of each NTI hidden state (rows) and another n_bases x n_bases matrix giving the transition probabilities between the NTI hidden states.

Note that the landing_N vectors be full length even though their tail end will be zero in many cases.

**Comment by matsen** [comment]
Closed by https://github.com/matsengrp/linearham/commit/719144edfa1760d7e6f9ab42f7323783343e8e2b

**Comment by matsen** [comment]
We now have the information described in the previous comment, and now we need to build a smooshable with an NTI region on the left.

Say we are looking at a D region. Say the d_l range is (d_ll, d_lr), and the relpos is m_d. Note that this uses Python range conventions, so d_lr is the first query index that is not included in the boundsbound. 

To build a match matrix with left NTI insertions for that D gene: 
* If m_g > d_ll, build a match matrix with left flex = d_lr-m_g-1 (d_lr - 1 is the last matched state, subtracting m_g gives the flex=0) and start=0 (where start is the offset in terms of germline coordinates). Then add dummy states by adding m_g-d_ll rows of zero on top of the match matrix. (see 🗡 below)
* If m_g <= d_ll, then build a match matrix with left flex = d_lr-d_ll, but start = d_ll-m_g.

🗡 The efficient way to do this will be to build a matrix of the eventual correct size filled with zeros, then extract an Eigen Block and store the match matrix inside of it.

**Comment by matsen** [comment]
Here's a description of how to build up the NTI matrix.

![x-000](https://cloud.githubusercontent.com/assets/112708/19703331/49f810a4-9ab8-11e6-8eaa-9b2766bc547e.png)

And just in case this is helpful:
![x-001](https://cloud.githubusercontent.com/assets/112708/19703405/8bcf4420-9ab8-11e6-936a-68ab9e689c1b.png)

**Comment by matsen** [comment]
Amrit's example:

![20161028_083239_1024](https://cloud.githubusercontent.com/assets/112708/19814311/8965bb56-9cf2-11e6-9906-b6c4eb0d6ab2.jpg)

**Comment by matsen** [comment]
Amrit's example (for NTI calculation):

![20161028_105023](https://cloud.githubusercontent.com/assets/112708/19817199/674a4980-9cff-11e6-8c08-b8e0766243b3.jpg)

In terms of base indices, this is 0, 1, 0, 2, 3, 0, 1, 1, 1, 3, 2, 3, 3, and the subset used to do NTI calculation is 2, 3, 0, 1, 1, 1.

**Comment by matsen** [comment]
Amrit's example for NTI calculation:

![20161028_083239_1024](https://cloud.githubusercontent.com/assets/112708/19817421/5d07462a-9d00-11e6-9edb-36b649922d0b.jpg)

In the flex notation for germline genes, if this was between V and D, it would be v_rl v_rr then d_ll d_lr.

In terms of base indices, this is 0, 1, 0, 2, 3, 0, 1, 1, 1, 3, 2, 3, 3, and the subset used to do NTI calculation is 2, 3, 0, 1, 1, 1.

**Comment by matsen** [comment]
The definition of flexbounds, in beautiful notebook paper:

![x-000](https://cloud.githubusercontent.com/assets/112708/19824406/e29f93dc-9d23-11e6-9ab1-bbc279d1d4d9.png)

**Comment by matsen** [comment]
Remaining things to do for this issue:

- restore tests
- make Smooshable constructors take Germline objects (not YAML)
- update things such that the Python notebook tests agree with the code.

**Comment by matsen** [comment]
Amrit's improved picture:

![image](https://cloud.githubusercontent.com/assets/112708/20118401/1d070a30-a5b9-11e6-8f0f-272950064215.png)

**Comment by matsen** [comment]
Relpos and flexbounds definitions, for posterity

![x-000](https://cloud.githubusercontent.com/assets/112708/20941514/81afca64-bbab-11e6-9e6d-917e80b3dc4c.png)

**Comment by dunleavy005** [comment]
Note: the V gene read position uncertainty in partis is determined by `[k_v_min, k_v_max)` (same for D genes).

**Comment by matsen** [comment]
@dunleavy005 say a little more? is the point here that it's a half-open interval or that it's the read position?

**Comment by dunleavy005** [comment]
The half open interval part.

**Comment by dunleavy005** [comment]
Edited.

**Comment by matsen** [comment]
Amrit's lovely picture:

![x-000](https://cloud.githubusercontent.com/assets/112708/21210429/d164f7b6-c22f-11e6-9ee8-d4c3075163be.png)
