### ISSUE TITLE
Remove matrix copy construction in Smooshable et al constructors?

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#34]
@bcclaywell, should we just not worry about the overhead of the copy constructor used in the Smooshable constructor? 
 
Seems like we are always building a matrix for the explicit purpose of putting in a Smooshable. Is there a way we could just move it into place?

We discussed this somewhere else, but putting it in an issue will remind me of the decision.

**Comment by bcclaywell** [comment]
It looks like Eigen matrices do have a `::swap()` function, so maybe you could take advantage of that by get away with writing some functions that take matrix rvalues, like

```
Smooshable::Smooshable(Eigen::MatrixXd&& marginal) {
  marginal_.swap(marginal);
  scaler_count_ = ScaleMatrix(marginal_);
};

SmooshablePtr BuildSmooshablePtr(
    Eigen::MatrixXd&& marginal) {
  return std::make_shared<Smooshable>(Smooshable(marginal));
}
```

and use it like

```
BuildSmooshablePtr(std::move(some_matrix));
```

when you know you're not going to need `some_matrix` again.

Note that I'm still working my way through Modern C++ so I may not have any idea what I'm talking about!

**Comment by matsen** [comment]
Cool!

**Comment by matsen** [comment]
Perhaps here: https://github.com/matsengrp/linearham/commit/1460e01cec4322baca06749e3f4021f6b276c03b#commitcomment-20721466

**Comment by dunleavy005** [comment]
smooshables are dead!! see #45
