### ISSUE TITLE
Python wrapper which builds an initial tree

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#36]
My thought is to just wrap FastTree.

1. load in partis output, including naive sequence
2. FastTree -> reroot using nw_utils -> drop root -> linearham

**Comment by matsen** [comment]
This should be RAxML, not FastTree, because we need the info file for pt.

**Comment by dunleavy005** [comment]
we're doing bayesian re-weighting using RevBayes trees as input now, no more optimization
