### ISSUE TITLE
biological validation data sets

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#46]
Following Duncan's idea in lab meeting, let's talk about biological validation data. Simulation data is straightforward.

* Chaim I guess has some data that would be appropriate due to depth of sampling?
* There are experiments in which a mouse is engineered with a given naive sequence.
* There are situations for HIV bnabs in which there are some samples that are close to the root, and some farther away. The samples close to the root "reveal" the naive sequence. Do we agree?

**Comment by dunleavy005** [comment]
we're doing vrc01 and pc64 analysis
