### ISSUE TITLE
remove mention of ubuntu 16.04 from readme

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/linearham#66]
The readme says it's been tested on ubuntu 16.04, but r-cran-data.table [looks](https://packages.ubuntu.com/search?keywords=r-cran-data.table) to only be for 18.04 or newer. Not yet sure if this matters.

**Comment by eharkins** [comment]
The readme may need to be updated, but I'm assuming it refers to the Docker image which is based on debian stretch (and it looks like ubuntu 16.04 is also based on debian stretch).

I would think this issue would manifest in failing to install r-cran-data.table in the [automatic docker image builds](https://github.com/matsengrp/linearham/actions). 

Thanks for pointing it out either way! Are you having issues installing r-cran-data.table?

**Comment by psathyrella** [comment]
yeah as far as i can tell there is no r-cran-data.table on 16.04. I suspect the difference is that 16.04 may be based on stretch, but it doesn't have exactly the same package set.

**Comment by dunleavy005** [comment]
FYI, Ubuntu 16.04 was my laptop OS (hence why I put it in the readme), it doesn't reflect anything in the dockerfile, you can remove it for sure. I put R packages in dockerfile so people knew the R package list required and I bet I just installed them within R on 16.04

**Comment by psathyrella** [comment]
let's change the readme say that if you're on the distro in the first line of the docker file you're probably ok.
