### ISSUE TITLE
make default tag on quay.io

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/linearham#72]
I'm not sure if that's exactly what I mean that we should do, but I'm working on the readme and I think what we currently say -- go follow this link to quay.io and guess what tag you should use -- isn't a good long term choice.

**Comment by eharkins** [comment]
If you pull without a tag it will use the default tag which is `latest`. We also say:
```
We recommended you use the most recent version-specific tag (e.g. v1.0.0, not latest) in order to allow for reproducibility
```

Open to any suggestions of changes to the README instructions
