### ISSUE TITLE
update readme with newer (?) output files

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/linearham#76]
@dunleavy005 i wonder if you could fill in a little info on some files that show up in the output directories but aren't listed in the docs? Mostly what I couldn't work out was where there are `XXX`s here https://github.com/matsengrp/linearham#output-files, e.g. like there's a second .trees file that seems to be a different file format than the one listed in the readme.

I'm also wondering if there's a reason we can't rename the `mcmciter[...]` and `burninfrac[...]` dirs to names that give some more clues how they're differentiated, and also so they're shorter? It gets really cumbersome to pass them around, maybe we can write the parameters to a log file (or maybe that's already done?).

**Comment by ksung25** [comment]
readme updated

**Comment by psathyrella** [comment]
Awesome! thank you.
